language: node_js
node_js:
  - stable
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "frednordell"
  - git config --local user.email "fred@nordells.nu"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  target_branch: release
  github_token:
    secure: wyCXurEoHkZ/v0jpYBNKC+JK/lMTq3aqHW3Grs4EEfTAHhdzze5WUqGgrhhXNaOXsEPqRMEvrl6qbZPzaCosonLVqo+Tzpq7tu4ifOWfGXLpENBMidzYPevSrSVwnspMHfGKKUcASEDxunW2YB03dAIju6LIGdAo6ULBUePmWR7Dblt9JoygvToZ/Ll34mn839EGLfGau8xs7uejpb10SmkZ03DRjPcyzyo0EUlSPTjWZkZcV70QIF1tY6gxjBgIJ24ID0lnyBJs4i7JCEslg0pxv59jB/KqC8ITDZNf45C6YqvcLseE+6KH/GvY4Xj2kt2AHPKOmvtBeBef1zM8/qY4T+XiBan5rZfsPMyAEq1pmtfNF8JfJQQVRTOsqaQ+HscfiftQpiLLygrX59K9zDseI4kw5BsqHkWkmkFKCnXB592JsLozaEZcvFaKnM04YvtojBlSXx+Ss/iVwNlr2Nx5yTqEYzhsBDW1miU6T8LVuy+r7jC1VwuDzRgkYAHfx7jLUkmS7J6rq+fcds9e4M1irF7kS853Ssv7ceQtYU3QWHB8dZpJPFK9POZwcznOEnXnTgfwkvCBGgJHIwzRw9yBk6+27VMGJnzLKhcWWfoik3Zpdgzlnz2nYyWCK4CVLphkjyik5tdUXB/gi4akZkP/639IoFb9LfK+9TLHoMg=
  keep_history: true
  local_dir: build
  on:
    branch: master 