language: node_js
node_js:
  - stable
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "frednordell"
  - git config --local user.email "fred@nordells.nu"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  target_branch: release
  github_token:
    secure: "nLXC5ORxp5DhZTopFdX1F+QIjTBRFZj2TfanoYyr/RNpPQiIdD1Haxjt4/E80WsU4Y9f+f1My9Yjsi16RzgxKzG5+/Pt1Y9oUfpdXrJ+hjqLgW/+DqgJ3qBxdEkeYoGL7i2U8hkAYKINF0BhS4Clhz9Kk6B5fnLI6lxq64Ts5uuiLQ8fqRaNfKZmdaVsNXA1EcDwEUJh3RQX6STBk/PTMQ002+odF6iNHk+3yMnOtqtYtUgpNZA5LnRXH6Wg7IUnDfATFYUoJSzctrJzgrEPXocDHEzu2P3haRoECy48iuoDD0Hdr0aG1rdpWHsUhhMU3ILOs7fH7E/nsNFrs5fm+HZb3ZUMUQ0bHENt5FJ7dQDEWE06T94P6xj4A20/FOOnrAd6d1LsgX3wwYS5TQAY5MyubCtdTmh4F594qTQxsu4xCp4RYwzj+Fngx0LwgUUQvtqNpMaCt3P/G915k0Gv/Z1+LkXsoSUkk2w2oI+XoMKLKr5Zhurc8DhFq/XMSFc6doc81x1ircYNy+Xwc4A07CchTbGy/BNq0D3m46YJenBOIdoZiP77CAIrVQFFPlpx88KZWIFXL9m/LdLLsYEk8hzbQhEpK2utQM7zain+Tr/Jb+KlwKqZOU2CFD4GLCCLC9UmO2Qo2ubBzv9nDHGZ0tzvN1z88SquEioSHQeo1T0="
  keep_history: true
  local_dir: build
  on:
    branch: master 